name: Docker Image Proxy caddy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
env:
  CADDY-TAG: "2.10"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: proxy caddy
        run:
          docker pull caddy:${{ env.CADDY-TAG }} &&
          docker tag caddy:${{ env.CADDY-TAG }} ${{ secrets.HUB_HOST }}/caddy:${{ env.CADDY-TAG }} &&
          docker login -u ${{ secrets.USERNAME}} -p ${{ secrets.PASSWORD}} ${{ secrets.HUB_HOST }} &&
          docker push ${{ secrets.HUB_HOST }}/caddy:${{ env.CADDY-TAG }}
