name: Docker Image Proxy n8n

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
env:
  N8N-TAG: 1.86.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: proxy n8nio
        run:
          docker pull docker.n8n.io/n8nio/n8n:${{ env.N8N-TAG }} &&
          docker tag docker.n8n.io/n8nio/n8n:${{ env.N8N-TAG }} ${{ secrets.HUB_HOST }}/n8nio:${{ env.N8N-TAG }} &&
          docker login -u ${{ secrets.USERNAME}} -p ${{ secrets.PASSWORD}} ${{ secrets.HUB_HOST }} &&
          docker push ${{ secrets.HUB_HOST }}/n8nio:${{ env.N8N-TAG }}
